sensor:

  # Top Layer Temperature Display - Outdoor Temperature
  - platform: homeassistant
    entity_id: sensor.local_weather_outdoor_temperature_patty_s_house
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "Out: %d°F / Down: %d°F / Up: %d°F"
            args: [ 
              '(int)round(x)', 
              '(int)round(id(downstairs_temperature).state)', 
              '(int)round(id(upstairs_temperature).state)' 
            ]

  # Top Layer Temperature Display - Downstairs Temperature
  - platform: homeassistant
    entity_id: sensor.downstairs_temperature
    id: downstairs_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "Out: %d°F / Down: %d°F / Up: %d°F"
            args: [ 
              '(int)round(id(outdoor_temperature).state)', 
              '(int)round(x)', 
              '(int)round(id(upstairs_temperature).state)' 
            ]

  # Top Layer Temperature Display - Upstairs Temperature
  - platform: homeassistant
    entity_id: sensor.upstairs_temperature
    id: upstairs_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "Out: %d°F / Down: %d°F / Up: %d°F"
            args: [ 
              '(int)round(id(outdoor_temperature).state)', 
              '(int)round(id(downstairs_temperature).state)', 
              '(int)round(x)' 
            ]

  # Office Blind Position
  - platform: homeassistant
    entity_id: cover.office_blind
    id: office_blind_position
    attribute: current_position

  # Centauri Carbon Print Progress
  - platform: homeassistant
    entity_id: sensor.centauri_carbon_percent_complete_helper
    id: centauri_carbon_percent
    on_value:
      - lvgl.label.update:
          id: print_progress_label
          text:
            format: "%.0f"
            args: [ 'x' ]

  # Filament Heater Humidity
  - platform: homeassistant
    entity_id: sensor.office_filament_heater_sensor_humidity
    id: filament_heater_humidity
    on_value:
      - lvgl.label.update:
          id: dryer_humidity_label
          text:
            format: "%.0f"
            args: [ 'x' ]



binary_sensor:

  # Office Evening Scene
  - platform: homeassistant
    id: office_scene_evening
    entity_id: binary_sensor.office_scene_evening
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_evening_button
          state:
            checked: !lambda return x;

  # Office Dimmed Scene
  - platform: homeassistant
    id: office_scene_dimmed
    entity_id: binary_sensor.office_scene_dimmed
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_dimmed_button
          state:
            checked: !lambda return x;

  # Office Calls Scene
  - platform: homeassistant
    id: office_scene_desk_call
    entity_id: binary_sensor.office_scene_desk_call
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_calls_button
          state:
            checked: !lambda return x;

  # Office Features Scene
  - platform: homeassistant
    id: office_scene_features
    entity_id: binary_sensor.office_scene_features
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda return x;

  # 3d Printer
  - platform: homeassistant
    id: office_3d_printer_power
    entity_id: switch.office_3d_printer_power
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: printer_power_button
            state:
              checked: !lambda return x;
        - lvgl.widget.update:
            id: printer_power_icon
            hidden: !lambda return x;
        - lvgl.widget.update:
            id: print_progress_container
            hidden: !lambda return !x;

  # Office Aircon
  - platform: homeassistant
    id: office_air_conditioner
    entity_id: switch.office_air_conditioner
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_aircon_button
          state:
            checked: !lambda return x;

  # Battery Charger
  - platform: homeassistant
    id: office_battery_charger
    entity_id: switch.battery_charger
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: battery_charger_button
          state:
            checked: !lambda return x;

  # Filament Heater 
  - platform: homeassistant
    id: office_filament_heater
    entity_id: switch.office_filament_heater_893b
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: filament_heater_button
            state:
              checked: !lambda return x;
        - lvgl.widget.update:
            id: filament_heater_icon
            hidden: !lambda return x;
        - lvgl.widget.update:
            id: dryer_humidity_container
            hidden: !lambda return !x;

  # Office Blind 100% (Open)
  - platform: template
    id: office_blind_100
    lambda: |-
      if (id(office_blind_position).has_state()) {
        return abs(id(office_blind_position).state - 100) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_open_button
          state:
            checked: !lambda return x;

  # Office Blind 66% (Semi Open)
  - platform: template
    id: office_blind_66
    lambda: |-
      if (id(office_blind_position).has_state()) {
        return abs(id(office_blind_position).state - 66) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_66_button
          state:
            checked: !lambda return x;

  # Office Blind 33% (Semi Closed)
  - platform: template
    id: office_blind_33
    lambda: |-
      if (id(office_blind_position).has_state()) {
        return abs(id(office_blind_position).state - 33) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_33_button
          state:
            checked: !lambda return x;

  # Office Blind 0% (Close)
  - platform: template
    id: office_blind_0
    lambda: |-
      if (id(office_blind_position).has_state()) {
        return abs(id(office_blind_position).state - 0) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_close_button
          state:
            checked: !lambda return x;

  # Office Storage Lights
  - platform: homeassistant
    id: office_storage_lights
    entity_id: light.office_storage
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: storage_lights_button
          state:
            checked: !lambda return x;

  # Network Rack
  - platform: homeassistant
    id: network_rack
    entity_id: light.office_network_rack
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: network_rack_button
          state:
            checked: !lambda return x;

  # Living Room Lights
  - platform: homeassistant
    id: living_room_lights_state
    entity_id: light.living_room_lights
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: living_room_lights_button
          state:
            checked: !lambda return x;

  # Living Room Lamps
  - platform: homeassistant
    id: living_room_lamps_state
    entity_id: light.living_room_lamps
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: living_room_lamps_button
          state:
            checked: !lambda return x;

  # Downstairs Climate Temperature
  - platform: homeassistant
    entity_id: climate.downstairs
    id: downstairs_climate_temp
    attribute: current_temperature
    on_value:
      - lvgl.label.update:
          id: downstairs_temp_label
          text:
            format: "Down: %d°F"
            args: [ '(int)round(x)' ]

  # Front Door Lock State
  - platform: homeassistant
    id: front_door_lock_state
    entity_id: lock.front_door
    attribute: state
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: front_door_lock_button
            state:
              checked: !lambda return x == "locked";
        - lvgl.label.update:
            id: front_door_lock_icon
            text: !lambda return (x == "locked") ? "$lock" : "$lock_open";

  # Living Room Sound Bar State
  - platform: homeassistant
    id: sound_bar_state
    entity_id: media_player.living_room_sound_bar
    attribute: state
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: living_room_sound_bar_button
            state:
              checked: !lambda return x == "playing";
        - lvgl.label.update:
            id: sound_bar_icon
            text: !lambda return (x == "playing") ? "$speaker" : "$speaker_off";

  # Master Bedroom Lights
  - platform: homeassistant
    id: master_bedroom_lights_state
    entity_id: light.master_bedroom_lights
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: master_bedroom_lights_button
          state:
            checked: !lambda return x;

  # Master Bedroom Temperature
  - platform: homeassistant
    entity_id: sensor.master_bedroom_temperature
    id: master_bedroom_temp_sensor
    on_value:
      - lvgl.label.update:
          id: master_bedroom_temp_display
          text:
            format: "%d°F"
            args: [ '(int)round(x)' ]
      - lvgl.label.update:
          id: master_bedroom_temp_display_2
          text:
            format: "%d°F"
            args: [ '(int)round(x)' ]

  # Keek's LEDs
  - platform: homeassistant
    id: keeks_leds_state
    entity_id: light.keek_s_leds
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: keeks_leds_button
          state:
            checked: !lambda return x;

  # Keek's Room Temperature
  - platform: homeassistant
    entity_id: sensor.keek_s_room_temperature
    id: keeks_room_temp_sensor
    on_value:
      - lvgl.label.update:
          id: keeks_room_temp_display
          text:
            format: "%d°F"
            args: [ '(int)round(x)' ]
      - lvgl.label.update:
          id: keeks_room_temp_display_2
          text:
            format: "%d°F"
            args: [ '(int)round(x)' ]

  # Upstairs Climate Temperature
  - platform: homeassistant
    entity_id: climate.upstairs
    id: upstairs_climate_temp
    attribute: current_temperature
    on_value:
      - lvgl.label.update:
          id: upstairs_temp_label
          text:
            format: "Up: %d°F"
            args: [ '(int)round(x)' ]
      - lvgl.label.update:
          id: upstairs_temp_display
          text:
            format: "%d°F"
            args: [ '(int)round(x)' ]

  # Kitchen Lights
  - platform: homeassistant
    id: kitchen_lights_state
    entity_id: light.kitchen_lights
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: kitchen_lights_button
          state:
            checked: !lambda return x;

  # Outdoor Lights
  - platform: homeassistant
    id: outdoor_lights_state
    entity_id: light.outdoor_lights
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: outdoor_lights_button
          state:
            checked: !lambda return x;

  # Driveway Lights Switch
  - platform: homeassistant
    id: driveway_lights_state
    entity_id: switch.driveway_lights
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: driveway_lights_button
          state:
            checked: !lambda return x;

  # Outdoor Temperature Display
  - platform: homeassistant
    entity_id: sensor.local_weather_outdoor_temperature_patty_s_house
    id: outdoor_temp_sensor_display
    on_value:
      - lvgl.label.update:
          id: outdoor_temp_display
          text:
            format: "%d°F"
            args: [ '(int)round(x)' ]

  # Greyson Room Temperature
  - platform: homeassistant
    entity_id: sensor.greyson_room_temperature
    id: greyson_room_temp_sensor
    on_value:
      - lvgl.label.update:
          id: greyson_room_temp_display
          text:
            format: "%d°F"
            args: [ '(int)round(x)' ]

  # Truck Switch
  - platform: homeassistant
    id: truck_state
    entity_id: switch.truck
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: truck_button
          state:
            checked: !lambda return x;

  # Truck Doors Lock State
  - platform: homeassistant
    id: truck_doors_lock_state
    entity_id: lock.truck_doors
    attribute: state
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: truck_doors_lock_button
            state:
              checked: !lambda return x == "locked";
        - lvgl.label.update:
            id: truck_doors_lock_icon
            text: !lambda return (x == "locked") ? "$lock" : "$lock_open";